### PR TITLE
refactor: expose parse_arg func

### PR DESCRIPTION
**Pull request by boriselec**
When using this image as base image it is useful to have args parser exposed

### CODE REVIEW

**Comment by fboulnois** [comment]
I don't see a tremendous advantage to doing this. Can you explain your use case?

**Comment by boriselec** [comment]
Basically i want to do this:
https://github.com/boriselec/stable-diffusion-server/blob/69c785df1349f35e0d0f52e7235e665de7a8ecb0/server.py#L68
https://github.com/boriselec/stable-diffusion-server/blob/69c785df1349f35e0d0f52e7235e665de7a8ecb0/server.py#L27

Get args on startup and then modify prompt on each request

**Comment by fboulnois** [comment]
Since this project has slowed down, I've decided to accept external contributions. I am using your PR as a test of this approach. I hope this works for you, and you should be credited appropriately.

Thank you for your PR!

**Comment by fboulnois** [comment]
@boriselec , one final question, sorry for the annoyance. I added a [CONTRIBUTING.md](https://github.com/fboulnois/stable-diffusion-docker/blob/main/CONTRIBUTING.md) guide and tried to make it as brief as possible, but added a [Developer Certificate of Origin section](https://github.com/fboulnois/stable-diffusion-docker/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) to ensure this project can actually use PRs that are submitted to it. Since your PR came in before this change, do you agree to the Developer Certificate of Origin?

**Pull request closed without merging**
